# Generated by Django 2.2.2 on 2019-08-01 06:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('available_stock', models.IntegerField(default=0)),
                ('alert_stock', models.IntegerField(default=0)),
                ('retail_unit_price', models.IntegerField(default=0)),
                ('purchase_unit_price', models.IntegerField(default=0)),
                ('measuring_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='retail.MeasuringUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_units', models.IntegerField()),
                ('no_of_return_units', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('net_amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sold_product', to='retail.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sold_product', to='retail.Sale')),
            ],
            options={
                'unique_together': {('sale', 'product')},
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(through='retail.SaleProduct', to='retail.Product'),
        ),
    ]
